### ISSUE TITLE
Hates Hodgepodge.

### ISSUE THREAD

**Issue by MagmaSlime123** [Hummel009/Legendary-Item#14]
Title.

[crash-2024-08-03_18.00.12-server.txt](https://github.com/user-attachments/files/16484285/crash-2024-08-03_18.00.12-server.txt)

Mod list is in report as well, if you need it.

**Comment by hummel009** [comment]
I see ClassNotFoundException, related to Spawn Eggs. My mods don't affect them... I think the problem can't be in my mod
