### ISSUE TITLE
Fix enchant

### ISSUE THREAD

**Issue by ghost** [Hummel009/Legendary-Item#15]
Can't enchant any item in the enchanting table.
I use the lasted 1.21 version.

**Comment by Hummel009** [comment]
Hello, thank you for the error message. Could you please tell me if everything worked correctly in version 1.20.X?

**Comment by Hummel009** [comment]
It's really weird. I'm running my forge, neoforge, and fabrik mod right now. I came to the conclusion that forge and neoforge broke enchantments after 1.20.5, because fabrik still works. I write the same code, but it works on factory, but it doesn't work on forge. I don't know what to do yet

**Comment by Hummel009** [comment]
It's really weird. I'm running my forge, neoforge, and fabric mod right now. I came to the conclusion that forge and neoforge broke enchantments after 1.20.5, because fabric still works. I write the same code, but it works on fabric, but it doesn't work on forge. I don't know what to do yet

**Comment by hummel009** [comment]
Thanks for the report, I fixed the problem for 1.21.1 and 1.20.6 both. Release is to be 29.08
